<?php

return [
    'developer_email' => env('AYAS_DEVELOPER_EMAIL', '1017website@gmail.com'),
    'content_sections' => [
        'Navigasi & Tombol' => [
            'loaderLabel' => ['label' => 'Teks Loading', 'en' => 'Preparing quality experience', 'id' => 'Menyiapkan pengalaman terbaik'],
            'navHome' => ['label' => 'Menu Beranda', 'en' => 'Home', 'id' => 'Beranda'],
            'navAbout' => ['label' => 'Menu Tentang', 'en' => 'About', 'id' => 'Tentang Kami'],
            'navProducts' => ['label' => 'Menu Produk', 'en' => 'Products', 'id' => 'Produk'],
            'navCapabilities' => ['label' => 'Menu Kapabilitas', 'en' => 'Capabilities', 'id' => 'Kapabilitas'],
            'navProcess' => ['label' => 'Menu Cara Kerja', 'en' => 'How We Work', 'id' => 'Cara Kerja'],
            'navNews' => ['label' => 'Menu Berita', 'en' => 'News', 'id' => 'Berita'],
            'navContact' => ['label' => 'Menu Kontak', 'en' => 'Contact', 'id' => 'Kontak'],
            'navCta' => ['label' => 'Tombol Header', 'en' => 'Start a conversation', 'id' => 'Mulai Percakapan'],
            'exploreProducts' => ['label' => 'Tombol Produk', 'en' => 'Explore Products', 'id' => 'Lihat Produk'],
            'discussNeeds' => ['label' => 'Tombol Diskusi', 'en' => 'Discuss Your Needs', 'id' => 'Diskusikan Kebutuhan'],
            'requestProduct' => ['label' => 'Tombol Informasi Produk', 'en' => 'Request Product Information', 'id' => 'Minta Informasi Produk'],
        ],
        'Hero' => [
            'heroEyebrow' => ['label' => 'Teks Kecil', 'en' => 'Local expertise, global reach.', 'id' => 'Keahlian lokal, jangkauan global.'],
            'heroTitle' => ['label' => 'Judul Hero', 'html' => true, 'en' => 'Your <em>Trusted</em> Partner for F&amp;B Supply.', 'id' => 'Mitra <em>Terpercaya</em> untuk Pasokan F&amp;B Anda.'],
            'heroText' => ['label' => 'Deskripsi Hero', 'textarea' => true, 'en' => 'A premium food & beverage supplier for HORECA, catering, and retail sectors across domestic (Indonesia) and export markets.', 'id' => 'Penyedia produk makanan & minuman berkualitas untuk industri HORECA, katering, dan ritel di pasar nasional (Indonesia) maupun ekspor.'],
            'coreMarket' => ['label' => 'Label Statistik 1', 'en' => 'Core market', 'id' => 'Pasar utama'],
            'marketReach' => ['label' => 'Label Statistik 2', 'en' => 'Market reach', 'id' => 'Jangkauan pasar'],
            'productLines' => ['label' => 'Label Statistik 3', 'en' => 'Product lines', 'id' => 'Lini produk'],
            'scrollDiscover' => ['label' => 'Petunjuk Gulir', 'en' => 'Scroll to discover', 'id' => 'Gulir untuk menjelajah'],
        ],
        'Marquee & Nilai' => [
            'warmFriendly' => ['label' => 'Nilai 1', 'en' => 'We Listen to Your Needs', 'id' => 'Mendengarkan Kebutuhan Anda'],
            'helpfulService' => ['label' => 'Nilai 2', 'en' => 'We Deliver the Best Solutions', 'id' => 'Memberikan Solusi Terbaik'],
            'professionalSupport' => ['label' => 'Nilai 3', 'en' => 'Professional Support', 'id' => 'Dukungan Profesional'],
            'domesticSupply' => ['label' => 'Marquee Domestik', 'en' => 'Domestic Supply', 'id' => 'Pasokan Domestik'],
            'exportCapability' => ['label' => 'Marquee Ekspor', 'en' => 'Export Capability', 'id' => 'Kapabilitas Ekspor'],
            'warmText' => ['label' => 'Deskripsi Nilai 1', 'textarea' => true, 'en' => 'Careful listening and clear communication help us understand what your business truly needs.', 'id' => 'Mendengarkan dengan saksama dan komunikasi yang jelas membantu kami memahami kebutuhan bisnis Anda.'],
            'helpfulText' => ['label' => 'Deskripsi Nilai 2', 'textarea' => true, 'en' => 'Practical product and supply solutions tailored to your quantity, timing, and market.', 'id' => 'Solusi produk dan pasokan yang praktis, disesuaikan dengan jumlah, waktu, dan pasar Anda.'],
            'supportText' => ['label' => 'Deskripsi Nilai 3', 'textarea' => true, 'en' => 'Trusted producers and a reliable supply chain.', 'id' => 'Produsen dan rantai pasok yang handal & dapat dipercaya.'],
        ],
        'Tentang Kami' => [
            'aboutLabel' => ['label' => 'Label Section', 'en' => 'Who We Are', 'id' => 'Tentang Kami'],
            'aboutTitle' => ['label' => 'Judul', 'html' => true, 'en' => 'Built to make food sourcing feel <em>simple, dependable, and personal.</em>', 'id' => 'Membuat pengadaan pangan terasa <em>mudah, andal, dan personal.</em>'],
            'aboutCopy' => ['label' => 'Deskripsi', 'textarea' => true, 'en' => 'We combine responsive service, carefully selected products, and consistent delivery to help our customers focus on serving their guests and growing their business.', 'id' => 'Kami memadukan layanan yang responsif, produk pilihan, dan pengiriman yang konsisten agar pelanggan dapat fokus melayani tamu dan mengembangkan bisnis.'],
            'horecaTitle' => ['label' => 'Judul Badge HORECA', 'en' => 'Made for HORECA', 'id' => 'Dibuat untuk HORECA'],
            'horecaText' => ['label' => 'Deskripsi Badge HORECA', 'textarea' => true, 'en' => 'Supporting hotels, restaurants, cafés, catering operations, and other food-service businesses.', 'id' => 'Mendukung hotel, restoran, kafe, operasional katering, dan bisnis jasa boga lainnya.'],
        ],
        'Produk' => [
            'productsLabel' => ['label' => 'Label Section', 'en' => 'Our Product Range', 'id' => 'Rangkaian Produk'],
            'productsTitle' => ['label' => 'Judul Section', 'textarea' => true, 'en' => 'Selected products for ambitious food businesses.', 'id' => 'Produk pilihan untuk bisnis kuliner yang terus berkembang.'],
            'productsCopy' => ['label' => 'Deskripsi Section', 'textarea' => true, 'en' => 'From locally supplied favourites to export-ready products, our range is selected to deliver quality, convenience, and dependable performance.', 'id' => 'Dari produk favorit untuk pasokan lokal hingga produk siap ekspor, rangkaian kami dipilih untuk memberikan kualitas, kemudahan, dan performa yang andal.'],
            'domesticOnly' => ['label' => 'Label Pasar Domestik', 'en' => 'Domestic Market Only (Indonesia)', 'id' => 'Khusus Pasar Domestik (Indonesia)'],
            'exportOnly' => ['label' => 'Label Pasar Ekspor', 'en' => 'Export Market Only', 'id' => 'Khusus Pasar Ekspor'],
        ],
        'Kapabilitas' => [
            'capabilityRing' => ['label' => 'Teks Lingkaran', 'en' => 'Local expertise · Global reach', 'id' => 'Keahlian lokal · Jangkauan global'],
            'capabilitiesLabel' => ['label' => 'Label Section', 'en' => 'Domestic & Export', 'id' => 'Domestik & Ekspor'],
            'capabilitiesTitle' => ['label' => 'Judul', 'textarea' => true, 'en' => 'Reliable movement from source to destination.', 'id' => 'Pergerakan andal dari sumber hingga tujuan.'],
            'capabilitiesCopy' => ['label' => 'Deskripsi', 'textarea' => true, 'en' => 'Our supply capability is designed for businesses that need responsiveness, product consistency, and practical coordination across domestic and export requirements.', 'id' => 'Kapabilitas pasokan kami dirancang untuk bisnis yang membutuhkan respons cepat, konsistensi produk, dan koordinasi praktis untuk kebutuhan domestik maupun ekspor.'],
            'marketChannels' => ['label' => 'Metrik 1', 'en' => 'Market channels', 'id' => 'Saluran pasar'],
            'coreProductLines' => ['label' => 'Metrik 2', 'en' => 'Core product lines', 'id' => 'Lini produk utama'],
            'horecaSegments' => ['label' => 'Metrik 3', 'en' => 'HORECA segments', 'id' => 'Segmen HORECA'],
            'responsiveSupport' => ['label' => 'Metrik 4', 'en' => 'Responsive support', 'id' => 'Dukungan responsif'],
        ],
        'Cara Kerja' => [
            'processLabel' => ['label' => 'Label Section', 'en' => 'How We Work', 'id' => 'Cara Kerja'],
            'processTitle' => ['label' => 'Judul Section', 'en' => 'Simple process. Clear communication.', 'id' => 'Proses sederhana. Komunikasi jelas.'],
            'processCopy' => ['label' => 'Deskripsi Section', 'textarea' => true, 'en' => 'A focused supply process designed to make every order easier to understand, coordinate, and deliver.', 'id' => 'Proses pasokan terarah yang membuat setiap pesanan lebih mudah dipahami, dikoordinasikan, dan dikirim.'],
            'step01' => ['label' => 'Nomor Tahap 1', 'en' => 'Step 01', 'id' => 'Langkah 01'],
            'shareNeeds' => ['label' => 'Judul Tahap 1', 'en' => 'Share Your Needs', 'id' => 'Sampaikan Kebutuhan'],
            'shareNeedsText' => ['label' => 'Deskripsi Tahap 1', 'textarea' => true, 'en' => 'Tell us the product, volume, schedule, and destination required for your operation.', 'id' => 'Sampaikan produk, volume, jadwal, dan tujuan yang dibutuhkan untuk operasional Anda.'],
            'step02' => ['label' => 'Nomor Tahap 2', 'en' => 'Step 02', 'id' => 'Langkah 02'],
            'productMatching' => ['label' => 'Judul Tahap 2', 'en' => 'Product Matching', 'id' => 'Pencocokan Produk'],
            'productMatchingText' => ['label' => 'Deskripsi Tahap 2', 'textarea' => true, 'en' => 'We recommend suitable products and prepare a clear supply proposal for review.', 'id' => 'Kami merekomendasikan produk yang sesuai dan menyiapkan proposal pasokan yang jelas untuk ditinjau.'],
            'step03' => ['label' => 'Nomor Tahap 3', 'en' => 'Step 03', 'id' => 'Langkah 03'],
            'orderCoordination' => ['label' => 'Judul Tahap 3', 'en' => 'Order Coordination', 'id' => 'Koordinasi Pesanan'],
            'orderCoordinationText' => ['label' => 'Deskripsi Tahap 3', 'textarea' => true, 'en' => 'Our team confirms availability, specifications, documentation, and fulfilment timing.', 'id' => 'Tim kami mengonfirmasi ketersediaan, spesifikasi, dokumen, dan waktu pemenuhan.'],
            'step04' => ['label' => 'Nomor Tahap 4', 'en' => 'Step 04', 'id' => 'Langkah 04'],
            'consistentDelivery' => ['label' => 'Judul Tahap 4', 'en' => 'Consistent Delivery', 'id' => 'Pengiriman Konsisten'],
            'consistentDeliveryText' => ['label' => 'Deskripsi Tahap 4', 'textarea' => true, 'en' => 'Your order is prepared and coordinated for dependable domestic or export delivery.', 'id' => 'Pesanan Anda disiapkan dan dikoordinasikan untuk pengiriman domestik atau ekspor yang andal.'],
        ],
        'Berita' => [
            'newsLabel' => ['label' => 'Label Section', 'en' => 'News & Activities', 'id' => 'Berita & Kegiatan'],
            'newsTitle' => ['label' => 'Judul Section', 'en' => 'Updates from our supply network.', 'id' => 'Kabar dari jaringan pasokan kami.'],
            'newsLead' => ['label' => 'Deskripsi Section', 'textarea' => true, 'en' => 'This space is ready for supply progress, export activities, and visits to the partner factories that support AYAS FOODLINK.', 'id' => 'Ruang ini disiapkan untuk kabar perkembangan pasokan, kegiatan ekspor, dan kunjungan ke pabrik mitra yang mendukung AYAS FOODLINK.'],
            'newsComingSoon' => ['label' => 'Label Kartu', 'en' => 'Updates coming soon', 'id' => 'Kabar segera hadir'],
            'newsReadMore' => ['label' => 'Tombol Baca', 'en' => 'Read details →', 'id' => 'Baca selengkapnya →'],
        ],
        'Kontak & Formulir' => [
            'contactLabel' => ['label' => 'Label Section', 'en' => 'Contact Us', 'id' => 'Hubungi Kami'],
            'contactTitle' => ['label' => 'Judul', 'html' => true, 'en' => 'Let’s support your business with <em>better supply.</em>', 'id' => 'Mari dukung bisnis Anda dengan <em>pasokan yang lebih baik.</em>'],
            'contactText' => ['label' => 'Deskripsi', 'textarea' => true, 'en' => 'Tell us what your business needs. Our team will respond with suitable product and supply information.', 'id' => 'Sampaikan kebutuhan bisnis Anda. Tim kami akan merespons dengan informasi produk dan pasokan yang sesuai.'],
            'addressLabel' => ['label' => 'Label Alamat', 'en' => 'Address', 'id' => 'Alamat'],
            'phoneLabel' => ['label' => 'Label Telepon', 'en' => 'Phone / WhatsApp', 'id' => 'Telepon / WhatsApp'],
            'websiteLabel' => ['label' => 'Label Website', 'en' => 'Website', 'id' => 'Situs Web'],
            'emailLabel' => ['label' => 'Label Email', 'en' => 'Email', 'id' => 'Email'],
            'formTitle' => ['label' => 'Judul Form', 'en' => 'Request Product Information', 'id' => 'Minta Informasi Produk'],
            'formLead' => ['label' => 'Deskripsi Form', 'en' => 'Complete the form, then choose WhatsApp or email.', 'id' => 'Lengkapi formulir, lalu pilih WhatsApp atau email.'],
            'nameLabel' => ['label' => 'Label Nama', 'en' => 'Name', 'id' => 'Nama'],
            'companyLabel' => ['label' => 'Label Perusahaan', 'en' => 'Company', 'id' => 'Perusahaan'],
            'productInterestLabel' => ['label' => 'Label Minat Produk', 'en' => 'Product Interest', 'id' => 'Produk yang Diminati'],
            'selectProduct' => ['label' => 'Pilihan Awal Produk', 'en' => 'Select a product', 'id' => 'Pilih produk'],
            'otherProduct' => ['label' => 'Pilihan Produk Lain', 'en' => 'Other product', 'id' => 'Produk lainnya'],
            'messageLabel' => ['label' => 'Label Pesan', 'en' => 'Message', 'id' => 'Pesan'],
            'sendWhatsApp' => ['label' => 'Tombol WhatsApp', 'en' => 'Send via WhatsApp', 'id' => 'Kirim via WhatsApp'],
            'sendEmail' => ['label' => 'Tombol Email', 'en' => 'Send via Email', 'id' => 'Kirim via Email'],
            'formNote' => ['label' => 'Catatan Form', 'textarea' => true, 'en' => 'Your chosen WhatsApp or email app will open; this website does not store your information.', 'id' => 'Aplikasi WhatsApp atau email pilihan Anda akan terbuka; situs ini tidak menyimpan informasi Anda.'],
            'namePlaceholder' => ['label' => 'Placeholder Nama', 'en' => 'Your name', 'id' => 'Nama Anda'],
            'companyPlaceholder' => ['label' => 'Placeholder Perusahaan', 'en' => 'Company name', 'id' => 'Nama perusahaan'],
            'phonePlaceholder' => ['label' => 'Placeholder Telepon', 'en' => 'Your WhatsApp number', 'id' => 'Nomor WhatsApp Anda'],
            'messagePlaceholder' => ['label' => 'Placeholder Pesan', 'textarea' => true, 'en' => 'Tell us the product, quantity, location, and timeline you need.', 'id' => 'Sampaikan produk, jumlah, lokasi, dan waktu yang Anda butuhkan.'],
            'emailPlaceholder' => ['label' => 'Placeholder Email', 'en' => 'name@company.com', 'id' => 'nama@perusahaan.com'],
            'contactMessageIntro' => ['label' => 'Pembuka Pesan WhatsApp', 'textarea' => true, 'en' => 'Hello AYAS FOODLINK, I would like to request product information.', 'id' => 'Halo AYAS FOODLINK, saya ingin meminta informasi produk.'],
            'contactEmailSubject' => ['label' => 'Subjek Email', 'en' => 'AYAS FOODLINK Product Information Request', 'id' => 'Permintaan Informasi Produk AYAS FOODLINK'],
        ],
        'Footer' => [
            'footerCopyright' => ['label' => 'Tulisan Hak Cipta', 'textarea' => true, 'en' => '© {year} AYAS FOODLINK. All rights reserved.', 'id' => '© {year} AYAS FOODLINK. Hak cipta dilindungi.'],
            'footerHome' => ['label' => 'Menu Beranda', 'en' => 'Home', 'id' => 'Beranda'],
            'footerAbout' => ['label' => 'Menu Tentang Kami', 'en' => 'About', 'id' => 'Tentang Kami'],
            'footerProducts' => ['label' => 'Menu Produk', 'en' => 'Products', 'id' => 'Produk'],
            'footerNews' => ['label' => 'Menu Berita', 'en' => 'News', 'id' => 'Berita'],
            'footerContact' => ['label' => 'Menu Kontak', 'en' => 'Contact', 'id' => 'Kontak'],
        ],
        'Detail Berita' => [
            'postBack' => ['label' => 'Kembali ke Berita', 'en' => '← Back to News', 'id' => '← Kembali ke Berita'],
            'postOther' => ['label' => 'Label Berita Lain', 'en' => 'Other news', 'id' => 'Berita lainnya'],
            'postCtaTitle' => ['label' => 'Judul CTA', 'en' => 'Need product or supply information?', 'id' => 'Membutuhkan informasi produk atau pasokan?'],
            'postCtaButton' => ['label' => 'Tombol CTA', 'en' => 'Contact AYAS FOODLINK →', 'id' => 'Hubungi AYAS FOODLINK →'],
            'postFooterBack' => ['label' => 'Link Footer', 'en' => 'Back to News', 'id' => 'Kembali ke Berita'],
            'postNote' => ['label' => 'Catatan Artikel', 'textarea' => true, 'en' => 'This page is ready to be updated with dates, photographs, locations, and verified activity details when the material is available.', 'id' => 'Halaman ini siap diperbarui dengan tanggal, foto, lokasi, dan detail kegiatan terverifikasi setelah materinya tersedia.'],
            'postGalleryLabel' => ['label' => 'Label Galeri (aksesibilitas)', 'en' => 'Article photo gallery', 'id' => 'Galeri foto artikel'],
        ],
    ],
    'media' => [
        'logo' => ['label' => 'Logo Header', 'default' => 'assets/logo-new.png'],
        'favicon' => ['label' => 'Favicon', 'default' => 'assets/favicon.png'],
        'hero_image' => ['label' => 'Gambar Hero', 'default' => 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1800&q=88'],
        'about_image' => ['label' => 'Gambar Tentang Kami', 'default' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1500&q=86'],
        'capability_image_main' => ['label' => 'Gambar Kapabilitas Utama', 'default' => 'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1400&q=86'],
        'capability_image_small' => ['label' => 'Gambar Kapabilitas Kecil', 'default' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=900&q=84'],
        'seo_og_image' => ['label' => 'Gambar Share SEO / Open Graph', 'default' => 'assets/images/warehouse-fallback.jpg'],
    ],
    'details' => [
        'company_name' => 'AYAS FOODLINK',
        'address' => 'Ruko Galaxi Bumi Permai J1-23A, Semolowaru, Kec. Sukolilo, Surabaya, Jawa Timur 60119',
        'phone' => '0812-345-666-999',
        'whatsapp' => '62812345666999',
        'email' => 'sales@ayasfoodlink.co.id',
        'instagram' => '@ayasfoodlink',
        'instagram_url' => 'https://www.instagram.com/ayasfoodlink/',
        'website' => 'ayasfoodlink.co.id',
        'meta_title' => 'AYAS FOODLINK — Your Trusted Partner for F&B Supply',
        'meta_description' => 'AYAS FOODLINK — your trusted partner for food and beverage supply across domestic and export markets.',
        'stat_1_value' => 'HORECA',
        'stat_2_value' => '2',
        'stat_3_value' => '4+',
        'metric_1_value' => '2',
        'metric_2_value' => '4',
        'metric_3_value' => '3',
        'metric_4_value' => '1:1',
    ],
    'seo' => [
        'canonical_url' => ['label' => 'URL Canonical Website', 'default' => 'https://ayasfoodlink.co.id', 'help' => 'Alamat utama website tanpa garis miring di akhir.'],
        'robots' => ['label' => 'Meta Robots', 'default' => 'index, follow', 'help' => 'Gunakan noindex, nofollow hanya saat website belum boleh ditemukan.'],
        'og_title' => ['label' => 'Judul Saat Dibagikan', 'default' => 'AYAS FOODLINK — Your Trusted Partner for F&B Supply'],
        'og_description' => ['label' => 'Deskripsi Saat Dibagikan', 'default' => 'AYAS FOODLINK — your trusted partner for food and beverage supply across domestic and export markets.', 'textarea' => true],
        'twitter_card' => ['label' => 'Tipe Twitter Card', 'default' => 'summary_large_image'],
        'google_site_verification' => ['label' => 'Google Site Verification', 'default' => '', 'help' => 'Isi hanya kode content dari Search Console, bukan seluruh tag HTML.'],
    ],
    'tracking' => [
        'meta_pixel_id' => ['label' => 'Meta Pixel ID', 'default' => '', 'placeholder' => '123456789012345'],
        'ga4_measurement_id' => ['label' => 'Google Analytics 4 ID', 'default' => '', 'placeholder' => 'G-XXXXXXXXXX'],
        'google_tag_id' => ['label' => 'Google Tag ID', 'default' => '', 'placeholder' => 'GT-XXXXXXXX'],
        'gtm_container_id' => ['label' => 'Google Tag Manager', 'default' => '', 'placeholder' => 'GTM-XXXXXXX'],
        'google_ads_conversion_id' => ['label' => 'Google Ads Conversion ID', 'default' => '', 'placeholder' => 'AW-XXXXXXXXX'],
        'google_ads_conversion_label' => ['label' => 'Google Ads Conversion Label', 'default' => '', 'help' => 'Dipakai saat pengunjung mengirim formulir/klik WhatsApp atau email.'],
    ],
    'qontak' => [
        'qontak_enabled' => ['label' => 'Aktifkan Integrasi', 'default' => '0', 'type' => 'checkbox'],
        'qontak_base_url' => ['label' => 'API Base URL', 'default' => 'https://api.mekari.com/qontak/chat/v1'],
        'qontak_access_token' => ['label' => 'Access Token', 'default' => '', 'type' => 'password', 'secret' => true, 'help' => 'Disimpan terenkripsi dan tidak pernah ditampilkan kembali.'],
        'qontak_channel_integration_id' => ['label' => 'Channel Integration ID', 'default' => ''],
        'qontak_message_template_id' => ['label' => 'WhatsApp Message Template ID', 'default' => ''],
        'qontak_template_language' => ['label' => 'Kode Bahasa Template', 'default' => 'id', 'placeholder' => 'id'],
        'qontak_webhook_secret' => ['label' => 'Webhook Secret', 'default' => '', 'type' => 'password', 'secret' => true, 'help' => 'Gunakan nilai acak panjang; webhook URL tersedia di bawah.'],
    ],
];
