<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title', 'Dashboard') — AYAS CMS</title><link rel="icon" href="{{ asset('assets/favicon.png') }}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600&display=swap" rel="stylesheet">@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="admin-body">
<aside class="admin-sidebar" id="adminSidebar"><button class="sidebar-close" type="button" data-sidebar-close aria-label="Tutup menu">&times;</button><a class="admin-logo" href="{{ route('admin.dashboard') }}"><img src="{{ asset('assets/logo-white.png') }}" alt="AYAS FOODLINK"><span>Content Manager</span></a>
<nav><small>RUANG KERJA</small>
@php($items=[['admin.dashboard','⌂','Ringkasan'],['admin.produk.index','◇','Produk'],['admin.berita.index','▤','Berita'],['admin.inquiries.index','✉','Pesan Masuk'],['admin.analytics','↗','Statistik'],['admin.settings.edit','⚙','Pengaturan']])
@foreach($items as [$route,$icon,$label])<a href="{{ route($route) }}" @class(['active'=>request()->routeIs(str_replace('.index','.*',$route)) || request()->routeIs($route)])><i>{{ $icon }}</i><span>{{ $label }}</span>@if($route==='admin.inquiries.index' && ($sidebarNewCount ?? 0)>0)<b>{{ $sidebarNewCount }}</b>@endif</a>@endforeach
</nav><div class="sidebar-bottom"><a href="{{ route('home') }}" target="_blank">↗ <span>Lihat website</span></a><form action="{{ route('admin.logout') }}" method="post">@csrf<button type="submit">⇥ <span>Keluar</span></button></form></div></aside>
<button class="sidebar-backdrop" type="button" data-sidebar-close aria-label="Tutup menu"></button>
<div class="admin-shell"><header class="admin-topbar"><button class="sidebar-toggle" type="button" data-sidebar-toggle aria-controls="adminSidebar" aria-expanded="false" aria-label="Buka menu">☰</button><div><p>{{ now()->translatedFormat('l, d F Y') }}</p><h2>@yield('header', 'Selamat datang')</h2></div><div class="admin-user"><span>{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><p><b>{{ auth()->user()->name }}</b><small>Administrator</small></p></div></header>
<main class="admin-main">@if(session('success'))<div class="admin-alert success"><span>✓</span>{{ session('success') }}<button onclick="this.parentElement.remove()">×</button></div>@endif @if($errors->any())<div class="admin-alert error"><span>!</span><div><b>Ada data yang perlu diperbaiki.</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div><button onclick="this.parentElement.remove()">×</button></div>@endif @yield('content')</main></div>
</body></html>
